general.import = ["~/.config/alacritty/themes/github_dark_default.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Retina"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "SemiBold"

[window]
dynamic_title = true
opacity = 0.95

[scrolling]
history = 10000
