general.import = ["~/.config/alacritty/themes/github_dark_default.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Retina"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "SemiBold"


# Window tweaks to make it pop
[window]
dynamic_title = true
opacity = 0.95

# [window.padding]
# x = 10
# y = 6

# Scrollback for better visibility
[scrolling]
history = 10000
